routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('product.all');
});

Auth::routes();

Route::get('/products/{term?}', 'ProductController@all')->name('product.all');
Route::get('/product/{id?}', 'ProductController@single')->name('product.single');
// Route::get('/products/search/{term}', 'ProductController@search')->name('product.search');

Route::group(['middleware' => 'auth'], function() {

	Route::get('/review/create/{product_id}', 'ProductReviewController@createPage')->name('review.create');
	Route::post('/review/create/{product_id}', 'ProductReviewController@create')->name('review.create');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/faq', 'HomeController@faq')->name('faq');


Route::group(['middleware' => 'notadmin', 'prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function() {

	Route::get('/login', 'LoginController@showLoginForm')->name('login');
	Route::post('/login', 'LoginController@login')->name('login');

});

Route::group(['middleware' => 'admin', 'prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function() {

	Route::get('/', 'HomeController@index')->name('admin.index');

	Route::get('/products', 'ProductController@all')->name('products.all');
	Route::get('/product/{id}', 'ProductController@single')->name('products.single');

	Route::get('/products/add', 'ProductController@addPage')->name('products.add');
	Route::post('/products/add', 'ProductController@add')->name('products.add');

	Route::get('/product/activetoggle/{id}', 'ProductController@activetoggle')->name('products.activetoggle');

	Route::get('/categories', 'CategoryController@all')->name('categories.all');
	Route::get('/catgeory/{id}', 'CategoryController@single')->name('categories.single');

	Route::get('/categories/add', 'CategoryController@addPage')->name('categories.add');
	Route::post('/categories/add', 'CategoryController@add')->name('categories.add');
	
	Route::get('/users', 'UserController@all')->name('users.all');
	
	Route::get('/reviews', 'ReviewController@all')->name('reviews.all');
	Route::get('/review/{id}', 'ReviewController@single')->name('reviews.single');
	Route::get('/review/togglestatus/{id}', 'ReviewController@toggleStatus')->name('reviews.togglestatus');
	
	Route::post('/logout', 'LoginController@logout')->name('logout');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public $timestamps = true;

    protected $guarded = [];
    
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProductController extends Controller
{
    public function all()
    {
    	$products = \App\Product::join('product_categories', 'products.category_id', 'product_categories.id')
    	->select(
    		'products.*',
    		'product_categories.title as category'
    	)->get();

    	return view('adminpanel.products.all')->with('products', $products);

    }

    public function single()
    {

    }

    public function addPage()
    {
    	$categories = \App\ProductCategory::all();

    	return view('adminpanel.products.add')->with('categories', $categories);
    }

    public function add(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|min:1|max:255',
            'category_id' => 'numeric|required',
            'price' => 'numeric|required|min:0',
        ]);

        $file = $request->image_link->store('public');

        $file = explode("/", $file);

        $file = $file[1];

        \App\Product::create([
            'title' => $request->input('title'),
            'description' => $request->input('description'),
            'category_id' => $request->input('category_id'),
            'price' => $request->input('price'),
            'image_link' => $file
        ]);

        return redirect()->route('admin.products.all')->with([
            'status' => 1,
            'message' => 'Successfully Added a New Product'
        ]);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ProductController extends Controller
{
    
    public function all($search_term = "", Request $request)
    {
        $search_term = $search_term ? $search_term : $request->input('q');  
        
        if($search_term) {

            $pattern = "%" . $search_term . "%";
            
            $products = \App\Product::where('title', 'LIKE', $pattern)->orWhere('description', 'LIKE', $pattern)->get();
        } else {

            $products = \App\Product::all();
        }


    	$categories = \App\ProductCategory::all();

    	return view('frontend.products.all')
        ->with('products', $products)
        ->with('categories', $categories)
        ->with('search_term', $search_term);
    }

    public function single($id = '')
    {
    	$product = \App\Product::find($id);
        $reviews = \App\ProductReview::join('users', 'product_reviews.user_id', 'users.id')
        ->select(
            'product_reviews.*',
            'users.name as reviewer',
            'users.email as reviewer_mail_id'
        )
        ->where('product_id', $id)
        ->where('allowed_by_admin', 1)
        ->get();

    	return view('frontend.products.single')
        ->with('product', $product)
        ->with('reviews', $reviews);
    }

    // public function search($term = "")
    // {
    //     $pattern = "%" . $term . "%";
        
    //     $products = \App\Product::where('title', 'LIKE', $pattern)->orWhere('description', 'LIKE', $pattern)->get();

    //     $categories = \App\ProductCategory::all();

    //     return view('frontend.products.all')->with('products', $products)->with('categories', $categories);
    // }
}

resources/views/adminpanel/products/add.blade.php
@extends('adminpanel.layouts.master')

@section('content')

<a class="btn btn-default" href="{{ route('admin.products.all') }}">Go Back (Products)</a>
<br>
<div class="row">
	<form method="post" class="form-horizontal" action="{{ route('admin.products.add') }}" enctype="multipart/form-data">
		{{ csrf_field() }}
		<div class="form-group">
			<label for="title">Title</label>
			<input type="text" name="title" class="form-control" id="title">
		</div>

		<div class="form-group">
			<label for="category">Category</label>
			<select name="category_id" class="form-control">
				@foreach($categories as $category)
				<option value="{{ $category->id }}">{{ $category->title }}</option>
				@endforeach
			</select>
		</div>

		<div class="form-group">
			<label for="category">Price</label>
			<input class="form-control" type="number" name="price" min="0">
		</div>

		<div class="form-group">
			<label for="image-link">Featured Image</label>
			<input type="file" name="image_link">
		</div>

		<div class="form-group">
			<label for="description">Description(optional)</label>
			<textarea id="description" name="description" class="form-control"></textarea>
		</div>

		<button type="submit" class="btn btn-primary" name="submit">Save</button>
	</form>
	
</div>


@endsection

resources/views/adminpanel/products/all.blade.php
@extends('adminpanel.layouts.master')

@section('content')
<a class="btn btn-success" href="{{ route('admin.products.add') }}">Add a Product</a>
<br>
<div class="row">
	<table class="table table-hover">
		<thead>
			<tr>
				<th>#</th>
				<th>Title</th>
				<th>Description</th>
				<th>Category</th>
				<th>Price</th>
				<th>Created</th>
				<th>Updated</th>
				<th>Active</th>
			</tr>
		</thead>
		<tbody>
			@foreach($products as $product)
			<tr>
				<td>{{ $loop->iteration }}</td>
				<td>{{ $product->title }}</td>
				<td>{{ $product->description }}</td>
				<td>{{ $product->category }}</td>
				<td>{{ $product->price }}</td>
				<td>{{ $product->created_at }}</td>
				<td>{{ $product->updated_at }}</td>
				<td>
					@if($product->active)
					<a class="btn btn-sm btn-success" href="#">Active</a>
					@else
					<a class="btn btn-sm btn-danger" href="#">De-active</a>
					@endif
			</tr>
			@endforeach
		</tbody>
	</table>
</div>
@endsection