routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('product.all');
});

Auth::routes();

Route::get('/products/{term?}', 'ProductController@all')->name('product.all');
Route::get('/product/{id?}', 'ProductController@single')->name('product.single');
// Route::get('/products/search/{term}', 'ProductController@search')->name('product.search');

Route::group(['middleware' => 'auth'], function() {

	Route::get('/review/create/{product_id}', 'ProductReviewController@createPage')->name('review.create');
	Route::post('/review/create/{product_id}', 'ProductReviewController@create')->name('review.create');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/faq', 'HomeController@faq')->name('faq');


Route::group(['middleware' => 'notadmin', 'prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function() {

	Route::get('/login', 'LoginController@showLoginForm')->name('login');
	Route::post('/login', 'LoginController@login')->name('login');

});

Route::group(['middleware' => 'admin', 'prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin'], function() {

	Route::get('/', 'HomeController@index')->name('admin.index');

	Route::get('/products', 'ProductController@all')->name('products.all');
	Route::get('/product/{id}', 'ProductController@single')->name('products.single');

	Route::get('/products/add', 'ProductController@addPage')->name('products.add');
	Route::post('/products/add', 'ProductController@add')->name('products.add');

	Route::get('/product/activetoggle/{id}', 'ProductController@activetoggle')->name('products.activetoggle');

	Route::get('/categories', 'CategoryController@all')->name('categories.all');
	Route::get('/catgeory/{id}', 'CategoryController@single')->name('categories.single');

	Route::get('/categories/add', 'CategoryController@addPage')->name('categories.add');
	Route::post('/categories/add', 'CategoryController@add')->name('categories.add');
	
	Route::get('/users', 'UserController@all')->name('users.all');
	
	Route::get('/reviews', 'ReviewController@all')->name('reviews.all');
	Route::get('/review/{id}', 'ReviewController@single')->name('reviews.single');
	Route::get('/review/togglestatus/{id}', 'ReviewController@toggleStatus')->name('reviews.togglestatus');
	
	Route::post('/logout', 'LoginController@logout')->name('logout');
});

resources/views/adminpanel/layouts/master.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'ECommerce') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/admin') }}">
                        {{ config('app.name', 'ECommerce') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">

                        @if (Auth::guard('admin')->check())
                        <li {{ strpos(Route::currentRouteName(), 'admin.categories') !== false ? 'class=active' : ''}}><a href="{{ route('admin.categories.all') }}">Categories</a></li>
                        <li {{ strpos(Route::currentRouteName(), 'admin.product') !== false ? 'class=active' : ''}}><a href="{{ route('admin.products.all') }}">Products</a></li>
                        <li {{ strpos(Route::currentRouteName(), 'admin.user') !== false ? 'class=active' : ''}}><a href="{{ route('admin.users.all') }}">Users</a></li>
                        <li {{ strpos(Route::currentRouteName(), 'admin.review') !== false ? 'class=active' : ''}}><a href="{{ route('admin.reviews.all') }}">Reviews</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::guard('admin')->user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ route('logout') }}"
                                        onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                        @else
                        <!-- Authentication Links -->
                        <li><a href="{{ route('admin.login') }}">Login</a></li>
                        <!-- <li><a href="{{ route('register') }}">Register</a></li> -->
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            @if(session('status') !== null)
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>Success!</strong> {{ session('message') }}.
            </div>
            @endif
            
            @yield('content')

        </div>

    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>